spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/subject_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Mybatis\u63a5\u7d9a\u8a2d\u5b9a
mybatis.mapper-locations=classpath:com/example/demo/dao/*.xml
mybatis.type-aliases-package=com.example.demo.entity
mybatis.configuration.map-underscore-to-camel-case=true
