spring.application.name=ec-order-app

# PostgreSQL\u63a5\u7d9a\u8a2d\u5b9a
spring.datasource.url=jdbc:postgresql://localhost:5433/ec_order_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JDBC\u30c9\u30e9\u30a4\u30d0
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis\u8a2d\u5b9a
mybatis.configuration.map-underscore-to-camel-case=true

# SQL\u30ed\u30b0\u8868\u793a
logging.level.com.example.ecorder.repository=DEBUG

# Mapper XML\u5834\u6240
mybatis.mapper-locations=classpath:mapper/*.xml